### ISSUE TITLE
Entry format

### ISSUE THREAD

**Issue by pshriwise** [clemlatz/road-trips#39]
Saw a card on this in the project this evening. I had the same thought earlier today. I'm thinking it would be nice to have some of the per-trip information in a YAML header at the top of the file with entries and photos at specified header levels. Something like:

```markdown
---
id: scotland
title: Road-Trip en Écosse
subtitle: Mathilde & Clément à la recherche du poney perdu
linkTitle: Écosse, juillet 2018
mapCenter:
  lat: 56.98220
  lng: -4.89193
---

# Randonnée surprise à Holyrood Park
## 13 juillet
## coords
  - 55.94529675574091
  -  -3.1670421592712046

Nos valises à peine posées au Salisbury Green Hotel, nous décidons de terminer cettte première journée par une petite promenade de le parc voisin de Holyrood. Naïf que nous sommes : dans les parcs de la capitale — en tout cas à Holyrood Park —, il y a des montagnes et on peut randonner pendant des heures. Bien entendu, nous avions laissé les chaussures et l'équipement de randonnée dans les valises. Malgré cela, une belle balade, avec à la clé une vue panoramique sur Edimbourg, l'occasion idéale de faire connaissance avec la capitaine écossaise.

### 1-2
Notre hôtel, le Salisbury Green, en bordure de Holyrood Park.

...
```

Does that seem about right?

**Comment by pshriwise** [comment]
Another option I've been toying around with is to use pure YAML. It's certainly not as flexible as markdown, but hasl all the structure needed for the photo-centric blog entries. It's still a significant step up in readability from JSON as well.

```yaml
---
id: scotland
title: Road-Trip en Écosse
subtitle: Mathilde & Clément à la recherche du poney perdu
linkTitle: Écosse, juillet 2018
mapCenter:
  lat: 56.98220
  lng: -4.89193
mapZoomLevels:
  desktop: 7
  mobile: 7
entries:
  id: 1
  title: Randonnée surprise à Holyrood Park
  date: 13 juillet
  coords:
    - "55.94529675574091"
    - "-3.1670421592712046"
  content: "Nos valises à peine posées au Salisbury Green Hotel, nous décidons de terminer cettte première journée 
             par une petite promenade de le parc voisin de Holyrood. Naïf que nous sommes : dans les parcs de la 
             capitale — en tout cas à Holyrood Park —, il y a des montagnes et on peut randonner pendant des 
             heures. Bien entendu, nous avions laissé les chaussures et l'équipement de randonnée dans les valises. 
             Malgré cela, une belle balade, avec à la clé une vue panoramique sur Edimbourg, l'occasion idéale de 
             faire connaissance avec la capitaine écossaise."
  photos:
    - id: "1-2"
      caption: Notre hôtel, le Salisbury Green, en bordure de Holyrood Park.
    - id: "1-14"
      caption: La vue sur Holyrood Park depuis les rues d'Edimbourg.
```

**Comment by iwazaru** [comment]
I like the idea of using Markdown with a YAML header (I think that's called frontmatter?). I've been missing rich text while blogging.

I think it would be even better to have one markdown file per entry, so directory structure would look like this:

```
trips/
|- scotland/
 |- trip.yaml
 |- entries/
  |- 1.yaml
  |- 2.yaml
```

the `trip.yaml` containg trip info:

```yaml
id: scotland
title: Road-Trip en Écosse
subtitle: Mathilde & Clément à la recherche du poney perdu
linkTitle: Écosse, juillet 2018
mapCenter:
  lat: 56.98220
  lng: -4.89193
mapZoomLevels:
  desktop: 7
  mobile: 7
```

and an entry file looking like this:

```markdown
---
id: 1
title: Randonnée surprise à Holyrood Park
date: 13 juillet
coords: ["55.94529675574091", "-3.1670421592712046"]
photos:
  - id: "1-2"
     caption: Notre hôtel, le Salisbury Green, en bordure de Holyrood Park.
  - id: "1-14"
    caption: La vue sur Holyrood Park depuis les rues d'Edimbourg.
--- 

Nos valises à peine posées au **Salisbury Green Hotel**, nous décidons de terminer cette première journée 
par une petite promenade de le parc voisin de Holyrood. Naïf que nous sommes : dans les parcs de la 
capitale — en tout cas à Holyrood Park —, il y a des montagnes et on peut randonner pendant des 
heures. 

Bien entendu, nous avions laissé les chaussures et l'équipement de randonnée dans les valises. 
Malgré cela, une belle balade, avec à la clé une vue panoramique sur Edimbourg, l'occasion idéale de 
faire connaissance avec la capitaine écossaise.
```

I would keep photos as YAML though to avoid complex markdown parsing, although Markdown would also allow to add other image in the text.

But as you said, using YAML instead of JSON would already be a great improvement.
